### PR TITLE
Remove unnecessary code in finalize auction

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**

### CODE REVIEW

**Comment by stevenlcf** [comment]
Why is this unnecessary?

**Comment by Xuefeng-Zhu** [comment]
@stevenlcf The first for loop should handle all case properly. And it is very rare that redundant winners got declared

**Comment by stevenlcf** [comment]
> @stevenlcf The first for loop should handle all case properly. And it is very rare that redundant winners got declared

What do you mean by "very rare"? Does it mean that it can still happen? If it happens, is it ok to handle this case with deleting the codes?

**Comment by Xuefeng-Zhu** [comment]
> If it happens, is it ok to handle this case with deleting the codes?

As I mentioned, it can be handled by the first loop. And the lender does not have incentives to declare more winners, since it will increase the interest rate

**Pull request merged**
